# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action","Comedy","Drama","Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
[["wis.admissions@windfield.ac.th","Khamnueng Janprung (Es)"],
["accountingmanager@windfield.ac.th","Yupa Sukhonphun (Apple)"],
["accounting.admin@windfield.ac.th","Onanong Songputkaew (Maild)"],
["workvisa+gik@windfield.ac.th","Thipwaree Zammit (Gik)"],
["workvisa+ning@windfield.ac.th","Suwimon Phaephet (Ning)"],
["purchase@windfield.ac.th","Rapeeporn Singkum (Annie)"],
["michelle.bernet@windfield.ac.th","Michelle Klara Bernet"],
["phakavin.ongtoa@windfield.ac.th","Phakavin Ongtoa (Ong)"],
["viescolaire@windfield.ac.th","Guillaume Rataud"],
["morgane.brouillet@windfield.ac.th","Morgane Brouillet"],
["marcnuxis@windfield.ac.th","Marc Nuxis"],
["sarah.odekerken@windfield.ac.th","Sarah Odekerken"],
["hana.srikhi@windfield.ac.th","Hana Srikhi"],
["nathalie.paolella@windfield.ac.th","Nathalie Paolella"],
["alice.sur@windfield.ac.th","Alice Sur"],
["marjorie.r@windfield.ac.th","Marjorie Romaldi"],
["yevan.bitard@windfield.ac.th","Yevan Bitard"],
["clement.cochet@windfield.ac.th","Clément Cochet"],
["arthur.assad@windfield.ac.th","Arthur Assad"],
["stephane.bauche@windfield.ac.th","Stéphane Bauche"],
["qureshey.nabila@windfield.ac.th","Nabila Qureshey"],
["bernardo.soler.camara@windfield.ac.th","Bernardo Soler-Camara"],
["carmen.martinez.funes@windfield.ac.th","Carmen Martinez Funes"],
["rosette.martine@windfield.ac.th","Marie Martine Rosette"],
["jordan.lesage@windfield.ac.th","Jordan Lesage"],
["grace@windfield.ac.th","Lily Grace Alcordo"],
["dylan.bethwaite@windfield.ac.th","Dylan Thomas Bethwaite"],
["daria.vinogradova@windfield.ac.th","Daria Vinogradova"],
["melanie.garofalo@windfield.ac.th","Melanie Erin Garofalo"],
["alexandra.goleva@windfield.ac.th","Alexandra Goleva"],
["andreas.solomou@windfield.ac.th","Andreas Solomou"],
["darren.laycock@windfield.ac.th","Darren David Laycock"],
["colleen.jardine@windfield.ac.th","Colleen Ann Jardine"],
["jean.watt@windfield.ac.th","Jean Watt"],
["ovi.gaidos@windfield.ac.th","Ovidiu-Vasile Gaidos"],
["doug.yahrmarkt@windfield.ac.th","Douglas Allan Yahrmarkt"],
["alex.thomas@windfield.ac.th","Alexander Thomas"],
["supervisor.student@windfield.ac.th","Candice Mautret"],
["jessica.jackson@windfield.ac.th","Jessica Mary Jackson"],
["lena.korostylova@windfield.ac.th","Olena Korostylova"],
["gregory.darryl@windfield.ac.th","Gregory Darryl Overend"],
["emma.faber@windfield.ac.th","Emma Faber"],
["lj.gouws@windfield.ac.th","Louis Jaques Gouws"],
["louisgouws@windfield.ac.th","Louis J.Gouws"],
["angel.cruz@windfield.ac.th","Angel Garcia Cruz"],
["david.smith@windfield.ac.th","David Smith"],
["akasia.kali@windfield.ac.th","Herivola Akasia Rarivonjanahary (Kali)"],
["marie.schmitt@windfield.ac.th","Marie Schmitt"],
["jessicaevans@windfield.ac.th","Jessica Claire Evans"],
["akhil.omanakuttan@windfield.ac.th","Akhil Omanakuttan"],
["vassana.churee@windfield.ac.th","Vassana Churee(Mook)"],
["jerryescala08@windfield.ac.th","Jerrymil Dunlao Escal"],
["erlene.mantawid@windfield.ac.th","Erlene Mantawid"],
["mud.nanawichit@windfield.ac.th","Nathawee Nanawichit (Mud)"],
["lidia.candela@windfield.ac.th","Lidia Gomez Candela"],
["agnieszka.mm@windfield.ac.th","Agnieszka Migdalska"],
["yann.fortune@windfield.ac.th","Yann Fortune"],
["ekaterina.krivonos@windfield.ac.th","Ekaterina Krivonos"],
["ayman.abady@windfield.ac.th","Ayman Nabil Abdelbary Hussien"],
["piyawat11@windfield.ac.th","Piyawat Saengkaeo (X)"],
["roeme.claassens@windfield.ac.th","Roeme Claassens"],
["antony.george@windfield.ac.th","Antony George Bailey"],
["nathalie.bernard@windfield.ac.th","Nathalie Bernard"],
["secretary.wis@windfield.ac.th","Piyapa Phengnoo (Nidnoy)"],
["karen.franks@windfield.ac.th","Karen Michelle Franks"],
["michael.moriarty@windfield.ac.th","Michael Daniel Moriarty"],
["library@windfield.ac.th","Natascha Petcharwut (Nam)"],
["lance@windfield.ac.th","Laurence Maravilla (Lance)"],
["Kanjana.y@windfield.ac.th","Kanjana Yahrmarkt (Lieu)"],
["Vanuch2324@windfield.ac.th","Vanuch Inthawong (Mint)"],
["kwan855@windfield.ac.th","Sirikhwan Pansiri (Kwan)"],
["juthamat.junwirat@windfield.ac.th","Juthamat Janwirat (Fai)"],
["nuchjaree.khampang@windfield.ac.th","Nuchjaree Khampang (Nuch)"],
["lin.meng@windfield.ac.th","Lin Meng (Liu)"],
["anyaphat.noonnak@windfield.ac.th","Anyaphat Noonnak (Kamin)"],
["orapim.aryamuang@windfield.ac.th","Orapim Aryamuang (Dede)"],
["patcharin.phuttharaksa@windfield.ac.th","Patcharin Phuttharaksa (Maew)"],
["jarinya.srisang@windfield.ac.th","Jarinya Srisang (Fern)"],
["thitanan.teanchot@windfield.ac.th","Thitanan Teanchot (Neung)"],
["nanwadee.jaipluem@windfield.ac.th","Nanwadee Jaipluem (Pui)"],
["surudee.srifa@windfield.ac.th","Surudee Srifa (Pui)"],
["somtawin.pilong@windfield.ac.th","Somtawin Pilong (Jek)"],
["naritsaraporn.choopram@windfield.ac.th","Naritsaraporn Choopram (Noi)"],
["jaran.buasam@windfield.ac.th","Jaran Buasam (Bang)"],
["chantima.jaidee@windfield.ac.th","Chantima Jaidee (Jan)"],
["chithalak.klapkaeo@windfield.ac.th","Chithalak Klapkaeo (Bum)"],
["jenjira.ketukaeo@windfield.ac.th","Jenjira Ketukaeo (Jan)"],
["suriyan.phunsahwat@windfield.ac.th","Suriyan Phunsahwat (Koong)"],
["jaew.harnsongkram@windfield.ac.th","Jaew Harnsongkram (Jaew)"],
["pranee.suksri@windfield.ac.th","Pranee Suksri (Noy)"],
["srinopparat.sahassanon@windfield.ac.th","Srinopparat Sahassanon (Nok)"],
["duangchai.suksaibua@windfield.ac.th","Duangchai Suksaibua (Tim)"],
["siriphan.kaewlek@windfield.ac.th","Siriphan Kaewlek (Toon)"],
["saowakhon.senlin@windfield.ac.th","Saowakhon Senlin (Sao)"],
["amelda.gouws@windfield.ac.th","Amelda Gouws"],
["marion.laage@windfield.ac.th","Marion Laage"],
["sophie.holdich@windfield.ac.th","Sophie Holdich"],
["claudia.alessia@windfield.ac.th","Claudia Alessia"],
["karen.moller@windfield.ac.th","Karen Elizabeth Moller"],
["troy.tucker@windfield.ac.th","Troy William Tucker"],
["hla.shein@windfield.ac.th","Hla Shein (Zaw)"],
["catherine.tainsh@windfield.ac.th"," Catherine Tainsh"],
["chantelle.smit@windfield.ac.th","Chantelle Smit"],
["pichet.khongjan@windfield.ac.th","Pichet Khongjan (Aul)"],
["it.samui@windfield.ac.th","Thanathon Kwanthong (Ice)"],
["wis.socialmedia@windfield.ac.th","Pantipa Intharayut (Bee)"],
["fenamae.estorque@windfield.ac.th","Fenamae Estorque"],
["pimchanok.sirirat@windfield.ac.th","Pimchanok Sirirat (Far)"],
["saruta.tehpuyu@windfield.ac.th","Saruta Tehpuyu (Chin)"],
["haruthai.srisang@windfield.ac.th","Haruthai Srisang (Fah)"],
["chaiwat.duangkun@windfield.ac.th","Mr. Chaiwat Duangkun (Boat)"],
["janjira.jantarat@windfield.ac.th","Ms. Janjira Jantarat (Am)"],
["lin.zaw@windfield.ac.th","Lin Thuya Zaw (Rain)"],
["thanhaphan.thongsung@windfield.ac.th","Thanhaphan Thongsung (Too)"],
["sylvie.prevost@windfield.ac.th"," Sylvie Prévot"],
["alice.lansard@windfield.ac.th","Alice Lansard"],
["elodie.larroque@windfield.ac.th","Elodie Larroque"],
["stephane.kergoat@windfield.ac.th","Stéphane Kergoat"],
["arthur.chaillot@windfield.ac.th"," Arthur Chaillot"],
["nadia.rios@windfield.ac.th"," Nadia Rios Acevedo"],
["sebastien.gein@windfield.ac.th"," Sébastien Gein"],
["serena.ferreira@windfield.ac.th","Serena Ferreira"],
["gregory.mclnerney@windfield.ac.th","Gregory Gregan Mclnerney"],
["charmain.feltrin@windfield.ac.th","Charmain Ann Feltrin"],
["richelle.malabriga@windfield.ac.th","Richelle Malabriga"],
["wis.nurse@windfield.ac.th"," Aira Jane Lagua"],
["jayford.osman@windfield.ac.th","Jayford Osman"],
["fleur.sorbets@windfield.ac.th","Fleur Valerie Sorbets Popovitch"],
["juanita.fredericks@windfield.ac.th","Juanita Fredericks"],
["lucie.lofaro@windfield.ac.th","Lucie Lofaro Bruzzo"],
["arthittaya.phanchana@windfield.ac.th","Arthittaya Phachama"],
["simon.felix@windfield.ac.th","Mr. Simon Félix"],
["kamilla.hesur@windfield.ac.th","Ms. Kamilla Hesur"],
["rosalyn.abenio@windfield.ac.th","Ms. Rosalyn Abenio"],
["rungnapa.tongsree@windfield.ac.th","Ms. Rungnapa Tongsree (Rung)"],
["cobus.uys@windfield.ac.th","Cobus Johan Uys"],
["luo.ruixue@windfield.ac.th","Ruixue Luo "],
["josephine.millet@windfield.ac.th"," Josephine millet"],
["natchapat.longlerit@windfield.ac.th","Ms. Natchapat Longlerit (Nenie)"]].each do |u|
  User.create_with(password: "1234").find_or_create_by!(name: u[1], email_address: u[0])
end

