# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action","Comedy","Drama","Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
[
["wis.admissions@windfield.ac.th","Khamnueng Janprung (Es)",2],
["accountingmanager@windfield.ac.th","Yupa Sukhonphun (Apple)",3],
["accounting.admin@windfield.ac.th","Onanong Songputkaew (Maild)",5],
["workvisa+gik@windfield.ac.th","Thipwaree Zammit (Gik)",6],
["workvisa+ning@windfield.ac.th","Suwimon Phaephet (Ning)",7],
["purchase@windfield.ac.th","Rapeeporn Singkum (Annie)",8],
["michelle.bernet@windfield.ac.th","Michelle Klara Bernet",38],
["phakavin.ongtoa@windfield.ac.th","Phakavin Ongtoa (Ong)",10],
["viescolaire@windfield.ac.th","Guillaume Rataud",11],
["morgane.brouillet@windfield.ac.th","Morgane Brouillet",12],
["marcnuxis@windfield.ac.th","Marc Nuxis",14],
["sarah.odekerken@windfield.ac.th","Sarah Odekerken",16],
["hana.srikhi@windfield.ac.th","Hana Srikhi",17],
["nathalie.paolella@windfield.ac.th","Nathalie Paolella",18],
["alice.sur@windfield.ac.th","Alice Sur",19],
["marjorie.r@windfield.ac.th","Marjorie Romaldi",20],
["yevan.bitard@windfield.ac.th","Yevan Bitard",21],
["clement.cochet@windfield.ac.th","Clément Cochet",25],
["arthur.assad@windfield.ac.th","Arthur Assad",26],
["stephane.bauche@windfield.ac.th","Stéphane Bauche",27],
["qureshey.nabila@windfield.ac.th","Nabila Qureshey",29],
["bernardo.soler.camara@windfield.ac.th","Bernardo Soler-Camara",30],
["carmen.martinez.funes@windfield.ac.th","Carmen Martinez Funes",31],
["rosette.martine@windfield.ac.th","Marie Martine Rosette",32],
["jordan.lesage@windfield.ac.th","Jordan Lesage",34],
["grace@windfield.ac.th","Lily Grace Alcordo",36],
["dylan.bethwaite@windfield.ac.th","Dylan Thomas Bethwaite",37],
["daria.vinogradova@windfield.ac.th","Daria Vinogradova",39],
["melanie.garofalo@windfield.ac.th","Melanie Erin Garofalo",40],
["alexandra.goleva@windfield.ac.th","Alexandra Goleva",42],
["andreas.solomou@windfield.ac.th","Andreas Solomou",43],
["darren.laycock@windfield.ac.th","Darren David Laycock",44],
["colleen.jardine@windfield.ac.th","Colleen Ann Jardine",45],
["jean.watt@windfield.ac.th","Jean Watt",46],
["ovi.gaidos@windfield.ac.th","Ovidiu-Vasile Gaidos",48],
["doug.yahrmarkt@windfield.ac.th","Douglas Allan Yahrmarkt",49],
["alex.thomas@windfield.ac.th","Alexander Thomas",50],
["supervisor.student@windfield.ac.th","Candice Mautret",51],
["jessica.jackson@windfield.ac.th","Jessica Mary Jackson",52],
["lena.korostylova@windfield.ac.th","Olena Korostylova",53],
["gregory.darryl@windfield.ac.th","Gregory Darryl Overend",55],
["emma.faber@windfield.ac.th","Emma Faber",56],
["lj.gouws@windfield.ac.th","Louis Jaques Gouws",57],
["louisgouws@windfield.ac.th","Louis J.Gouws",58],
["angel.cruz@windfield.ac.th","Angel Garcia Cruz",59],
["david.smith@windfield.ac.th","David Smith",60],
["akasia.kali@windfield.ac.th","Herivola Akasia Rarivonjanahary (Kali)",61],
["marie.schmitt@windfield.ac.th","Marie Schmitt",62],
["jessicaevans@windfield.ac.th","Jessica Claire Evans",63],
["akhil.omanakuttan@windfield.ac.th","Akhil Omanakuttan",64],
["vassana.churee@windfield.ac.th","Vassana Churee(Mook)",66],
["jerryescala08@windfield.ac.th","Jerrymil Dunlao Escal",67],
["erlene.mantawid@windfield.ac.th","Erlene Mantawid",68],
["mud.nanawichit@windfield.ac.th","Nathawee Nanawichit (Mud)",71],
["lidia.candela@windfield.ac.th","Lidia Gomez Candela",72],
["agnieszka.mm@windfield.ac.th","Agnieszka Migdalska",73],
["yann.fortune@windfield.ac.th","Yann Fortune",74],
["ekaterina.krivonos@windfield.ac.th","Ekaterina Krivonos",75],
["ayman.abady@windfield.ac.th","Ayman Nabil Abdelbary Hussien",76],
["piyawat11@windfield.ac.th","Piyawat Saengkaeo (X)",69],
["roeme.claassens@windfield.ac.th","Roeme Claassens",54],
["antony.george@windfield.ac.th","Antony George Bailey",77],
["nathalie.bernard@windfield.ac.th","Nathalie Bernard",28],
["secretary.wis@windfield.ac.th","Piyapa Phengnoo (Nidnoy)",4],
["karen.franks@windfield.ac.th","Karen Michelle Franks",79],
["michael.moriarty@windfield.ac.th","Michael Daniel Moriarty",80],
["library@windfield.ac.th","Natascha Petcharwut (Nam)",82],
["lance@windfield.ac.th","Laurence Maravilla (Lance)",83],
["Kanjana.y@windfield.ac.th","Kanjana Yahrmarkt (Lieu)",85],
["Vanuch2324@windfield.ac.th","Vanuch Inthawong (Mint)",86],
["kwan855@windfield.ac.th","Sirikhwan Pansiri (Kwan)",87],
["juthamat.junwirat@windfield.ac.th","Juthamat Janwirat (Fai)",89],
["nuchjaree.khampang@windfield.ac.th","Nuchjaree Khampang (Nuch)",90],
["lin.meng@windfield.ac.th","Lin Meng (Liu)",92],
["anyaphat.noonnak@windfield.ac.th","Anyaphat Noonnak (Kamin)",94],
["orapim.aryamuang@windfield.ac.th","Orapim Aryamuang (Dede)",96],
["patcharin.phuttharaksa@windfield.ac.th","Patcharin Phuttharaksa (Maew)",97],
["jarinya.srisang@windfield.ac.th","Jarinya Srisang (Fern)",98],
["thitanan.teanchot@windfield.ac.th","Thitanan Teanchot (Neung)",99],
["nanwadee.jaipluem@windfield.ac.th","Nanwadee Jaipluem (Pui)",101],
["surudee.srifa@windfield.ac.th","Surudee Srifa (Pui)",103],
["somtawin.pilong@windfield.ac.th","Somtawin Pilong (Jek)",105],
["naritsaraporn.choopram@windfield.ac.th","Naritsaraporn Choopram (Noi)",106],
["jaran.buasam@windfield.ac.th","Jaran Buasam (Bang)",108],
["chantima.jaidee@windfield.ac.th","Chantima Jaidee (Jan)",109],
["chithalak.klapkaeo@windfield.ac.th","Chithalak Klapkaeo (Bum)",110],
["jenjira.ketukaeo@windfield.ac.th","Jenjira Ketukaeo (Jan)",111],
["suriyan.phunsahwat@windfield.ac.th","Suriyan Phunsahwat (Koong)",112],
["jaew.harnsongkram@windfield.ac.th","Jaew Harnsongkram (Jaew)",113],
["pranee.suksri@windfield.ac.th","Pranee Suksri (Noy)",114],
["srinopparat.sahassanon@windfield.ac.th","Srinopparat Sahassanon (Nok)",115],
["duangchai.suksaibua@windfield.ac.th","Duangchai Suksaibua (Tim)",116],
["siriphan.kaewlek@windfield.ac.th","Siriphan Kaewlek (Toon)",117],
["saowakhon.senlin@windfield.ac.th","Saowakhon Senlin (Sao)",118],
["amelda.gouws@windfield.ac.th","Amelda Gouws",119],
["marion.laage@windfield.ac.th","Marion Laage",120],
["sophie.holdich@windfield.ac.th","Sophie Holdich",141],
["claudia.alessia@windfield.ac.th","Claudia Alessia",142],
["karen.moller@windfield.ac.th","Karen Elizabeth Moller",143],
["troy.tucker@windfield.ac.th","Troy William Tucker",81],
["hla.shein@windfield.ac.th","Hla Shein (Zaw)",107],
["catherine.tainsh@windfield.ac.th"," Catherine Tainsh",144],
["chantelle.smit@windfield.ac.th","Chantelle Smit",145],
["pichet.khongjan@windfield.ac.th","Pichet Khongjan (Aul)",104],
["it.samui@windfield.ac.th","Thanathon Kwanthong (Ice)",123],
["wis.socialmedia@windfield.ac.th","Pantipa Intharayut (Bee)",124],
["fenamae.estorque@windfield.ac.th","Fenamae Estorque",125],
["pimchanok.sirirat@windfield.ac.th","Pimchanok Sirirat (Far)",126],
["saruta.tehpuyu@windfield.ac.th","Saruta Tehpuyu (Chin)",127],
["haruthai.srisang@windfield.ac.th","Haruthai Srisang (Fah)",128],
["chaiwat.duangkun@windfield.ac.th","Chaiwat Duangkun (Boat)",129],
["janjira.jantarat@windfield.ac.th","Janjira Jantarat (Am)",130],
["lin.zaw@windfield.ac.th","Lin Thuya Zaw (Rain)",131],
["thanhaphan.thongsung@windfield.ac.th","Thanhaphan Thongsung (Too)",132],
["sylvie.prevost@windfield.ac.th"," Sylvie Prévot",134],
["alice.lansard@windfield.ac.th","Alice Lansard",135],
["elodie.larroque@windfield.ac.th","Elodie Larroque",136],
["stephane.kergoat@windfield.ac.th","Stéphane Kergoat",137],
["arthur.chaillot@windfield.ac.th"," Arthur Chaillot",138],
["nadia.rios@windfield.ac.th"," Nadia Rios Acevedo",139],
["sebastien.gein@windfield.ac.th"," Sébastien Gein",140],
["serena.ferreira@windfield.ac.th","Serena Ferreira",146],
["gregory.mclnerney@windfield.ac.th","Gregory Gregan Mclnerney",147],
["charmain.feltrin@windfield.ac.th","Charmain Ann Feltrin",148],
["richelle.malabriga@windfield.ac.th","Richelle Malabriga",149],
["wis.nurse@windfield.ac.th"," Aira Jane Lagua",150],
["jayford.osman@windfield.ac.th","Jayford Osman",151],
["fleur.sorbets@windfield.ac.th","Fleur Valerie Sorbets Popovitch",152],
["juanita.fredericks@windfield.ac.th","Juanita Fredericks",153],
["lucie.lofaro@windfield.ac.th","Lucie Lofaro Bruzzo",154],
["arthittaya.phanchana@windfield.ac.th","Arthittaya Phachama",155],
["simon.felix@windfield.ac.th","Simon Félix",156],
["kamilla.hesur@windfield.ac.th","Kamilla Hesur",157],
["rosalyn.abenio@windfield.ac.th","Rosalyn Abenio",158],
["rungnapa.tongsree@windfield.ac.th","Rungnapa Tongsree (Rung)",159],
["cobus.uys@windfield.ac.th","Cobus Johan Uys",160],
["luo.ruixue@windfield.ac.th","Ruixue Luo",162],
["josephine.millet@windfield.ac.th"," Josephine millet",163],
["natchapat.longlerit@windfield.ac.th","Natchapat Longlerit (Nenie)",166]
].each do |u|
  User.create_with(password: "1234").find_or_create_by!(email_address: u[0], name: u[1], staff_id: u[2])
end

[
["Sick leave (French)","leave_date > return_date (e.g., 28-02-2026 > 02-03-2026)",["marion.laage@windfield.ac.th","accountingmanager@windfield.ac.th","hr@windfield.ac.th"]],
["Sick leave (British)","leave_date > return_date (e.g., 28-02-2026 > 02-03-2026)",["amelda.gouws@windfield.ac.th","accountingmanager@windfield.ac.th","hr@windfield.ac.th"]],
["Sick leave (Thai Staff)","leave_date > return_date (e.g., 28-02-2026 > 02-03-2026)",["accountingmanager@windfield.ac.th","hr@windfield.ac.th"]],
["Hour Leave (French)","date_and_time (e.g., 28-02-2026 09:30-13:00)",["marion.laage@windfield.ac.th"]],
["Hour Leave (British)","date_and_time (e.g., 28-02-2026 09:30-13:00)",["amelda.gouws@windfield.ac.th"]],
["Hour Leave (Thai Staff)","date_and_time (e.g., 28-02-2026 09:30-13:00)",["accountingmanager@windfield.ac.th"]],
["Personal Leave (French)","leave_date > return_date (e.g., 28-02-2026 > 02-03-2026)",["marion.laage@windfield.ac.th","accountingmanager@windfield.ac.th","hr@windfield.ac.th"]],
["Personal Leave (British)","leave_date > return_date (e.g., 28-02-2026 > 02-03-2026)",["amelda.gouws@windfield.ac.th","accountingmanager@windfield.ac.th","hr@windfield.ac.th"]],
["Personal Leave (Thai Staff)","leave_date > return_date (e.g., 28-02-2026 > 02-03-2026)",["accountingmanager@windfield.ac.th","hr@windfield.ac.th"]],
["Others (French)","leave_date > return_date (e.g., 28-02-2026 > 02-03-2026)",["marion.laage@windfield.ac.th","accountingmanager@windfield.ac.th","hr@windfield.ac.th"]],
["Others (British)","leave_date > return_date (e.g., 28-02-2026 > 02-03-2026)",["amelda.gouws@windfield.ac.th","accountingmanager@windfield.ac.th","hr@windfield.ac.th"]],
["Purchase (French)","item_description, image and/or link (e.g., 4 bundles of Craft Paper A4/1.3mm from https://s.lazada.co.th/s.ZdkPiC total 300 Baht)",["marion.laage@windfield.ac.th","purchase@windfield.ac.th","accountingmanager@windfield.ac.th"]],
["Purchase (British)","item_description, image and/or link (e.g., 4 bundles of Craft Paper A4/1.3mm from https://s.lazada.co.th/s.ZdkPiC total 300 Baht)",["amelda.gouws@windfield.ac.th","purchase@windfield.ac.th","accountingmanager@windfield.ac.th"]],
["Purchase (Thai)","item_description, image and/or link (e.g., 4 bundles of Craft Paper A4/1.3mm from https://s.lazada.co.th/s.ZdkPiC total 300 Baht)",["purchase@windfield.ac.th","accountingmanager@windfield.ac.th"]],
["School Trip (French)","Share the link to your School Trip Form",["marion.laage@windfield.ac.th","thaidirector@windfield.ac.th","secretary@windfield.ac.th","regis@windfield.ac.th","accountingmanager@windfield.ac.th"]],
["School Trip (British)","Share the link to your School Trip Form",["amelda.gouws@windfield.ac.th","thaidirector@windfield.ac.th","secretary@windfield.ac.th","regis@windfield.ac.th","accountingmanager@windfield.ac.th"]]
].each do |pc|
  PostCategory.find_or_create_by!(name: pc[0], pattern: pc[1], approvers: pc[2])
end




